### PR TITLE
add test for changing editor content

### PR DESCRIPTION
**Pull request by rlivsey**
Failing test demonstrating issue with changing the editor's content

### CODE REVIEW

**Comment by rlivsey** [comment]
This passes, but I assume it's because the dependencies are cached?

**Comment by rlivsey** [comment]
@bantic I just ran a git bisect on mobiledoc-kit between `0.7.0` and master and it points to https://github.com/bustlelabs/mobiledoc-kit/commit/1e474338b787320632f703507d034cb880cdac49 being when this starts to fail.

The weird thing is that changing the document causes the editor to be torn down and re-built from scratch, so maybe there could be a leak of some-kind where re-building the editor keeps some state around from the previous version? 

I'll dig a little further later tonight if I get a chance.

**Comment by bantic** [comment]
@rlivsey Thanks for adding this. The changes in https://github.com/bustlelabs/mobiledoc-kit/pull/273 should fix it.

The issue was that the second editor (after the first one is torn-down) incorrectly believed it had a valid cursor selection prior to being rendered. This was because when the first editor rendered it focused the cursor on the editor element.
When it was torn down the selection remained and the second editor attempted to figure out how the window's selection corresponded to its post abstract, but this errored because it had not rendered and there was no render tree for it yet.

**Comment by bantic** [comment]
I reran CI to force this test to fail. After the other changes are merged I'll rerun it again and it should pass then. :)

**Comment by rlivsey** [comment]
Awesome stuff, thanks!

**Comment by bantic** [comment]
I cherry-picked your test and opened a separate PR (#39) (it has to be rebased against master to pick up the changes to travis.yml that opted in to phantom 2 in order to get the tests to pass).
thanks again @rlivsey!

**Pull request closed without merging**
